### ISSUE TITLE
TStyledSpeedButton.Tag always 0

### ISSUE THREAD

**Issue by kursatturkay** [EtheaDev/StyledComponents#19] opened 2024-06-09 17:22 UTC
eg:
Btn1:TStyledSpeedButton;
.....
Btn1.Tag:=9;
caption:=Btn1.Tag.ToString; // returns 0

tag property cannot be set in runtime. and designtime. its always 0.
tested.

GetTag func returns wrong Tag. 
returns
Btn1.Render.Tag. not Btn1.Tag
also SetTag has same behaviour.

temporary using "HelpContext" property instead of Tag.

**Comment by carloBarazzetta** [comment] 2024-06-10 06:18
I cannot reproduce the issue: wich versione are you using?

**Comment by kursatturkay** [comment] 2024-06-10 19:58
[bug12024_06_10_(22;54).zip](https://github.com/user-attachments/files/15778409/bug12024_06_10_.22.54.zip)
1-create new project.
add a StyledSpeedButton.
Set button1.Tag=1 in designtime.
than test if Tag=1 in button1 click event
result=Tag=0

sample project attached.

**Comment by carloBarazzetta** [comment] 2024-06-10 22:09
Sorry, I've tested with TStyledButton... to solve add those lines into  Vcl.StyledButton.pas unit:
line 963:    property Tag;
line 1481:    property Tag;
In the next release it will be fixed...

**Comment by carloBarazzetta** [comment] 2024-06-17 08:12
Fixed in the latest release

**Closed by carloBarazzetta** 2024-06-17 08:12 UTC
