### ISSUE TITLE
Order of TStyledToolbarButtons on TStyledToolbar

### ISSUE THREAD

**Issue by lancerasmussen** [EtheaDev/StyledComponents#20] opened 2024-07-25 18:08 UTC
Is there a way to change the index order of the buttons on the toolbar without having to go to the DFM source and cut and pasting the button block to the order to use?
 3.60 installed on Delphi 12.

**Comment by carloBarazzetta** [comment] 2024-07-26 13:10
When you drag-drop the button to change the position, the order of the index is not changed, like in the standard toolbar... or the standard toolbar behave differently?

**Comment by carloBarazzetta** [comment] 2024-07-31 20:30
Fixed in 3.6.1

**Closed by carloBarazzetta** 2024-07-31 20:30 UTC

**Comment by carloBarazzetta** [comment] 2024-08-01 07:57
Please give me a feed-back if the problem is resolved for you!

**Comment by lancerasmussen** [comment] 2024-08-01 22:16
Resolved
